[phases.setup]
nixPkgs = [
  "chromium",
  "nss",
  "atk",
  "cups",
  "libdrm",
  "libxkbcommon",
  "libXcomposite",
  "libXdamage",
  "libXrandr",
  "libgbm",
  "alsaLib",
  "pango",
  "libXScrnSaver",
  "libxshmfence",
  "mesa",
  "cairo"
] 