[phases.setup]
nixPkgs = [
  "chromium",
  "nss",
  "atk",
  "cups",
  "libdrm",
  "libxkbcommon",
  "libxrandr",
  "libgbm",
  "alsa-lib",
  "pango",
  "libxss",
  "libxshmfence",
  "mesa",
  "cairo"
] 