[build]
builder = "nixpacks"
buildCommand = "npm run build"

[services]
[[services.web]]
name = "novi-app"
command = "npm run start:prod"
healthcheckPath = "/health"
healthcheckTimeout = 300
memoryLimit = "1G"

# Environment variables
[env]
NODE_ENV = "production" 
