[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "npm run start:web"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
memoryLimit = "512M"

[services]
[[services.workers]]
name = "whatsapp-bot"
command = "npm start"
memoryLimit = "512M" 