[build]
builder = "nixpacks"
buildCommand = "npm run build"

[services]
[[services.web]]
name = "web"
command = "npm run start:prod"
healthcheckPath = "/health"
healthcheckTimeout = 300
memoryLimit = "512M"

[[services.workers]]
name = "whatsapp-bot"
command = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
memoryLimit = "512M"

# Environment variables for port separation
[env]
BOT_PORT = "3001" 
