[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "node scripts/railway-start.js"
healthcheckPath = "/health"
healthcheckTimeout = 300

[services]
[[services.web]]
name = "web"
command = "node scripts/railway-start.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
memoryLimit = "512M"

[[services.workers]]
name = "whatsapp-bot"
command = "node scripts/simple-bot-start.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
memoryLimit = "512M"
port = "3001" 
